http:
  routers:
    auth:
      rule: "Host(`abc`) && PathPrefix(`/api/v1/auth`)"
      service: auth
      tls:
        certResolver: certificates
    proxy:
      rule: "Host(`abc`) && PathPrefix(`/api/v1`)"
      middlewares:
        - auth
      service: proxy
      tls:
        certResolver: certificates
    upload:
      rule: "Host(`abc`) && PathPrefix(`/api/v1/attachments`) || PathPrefix(`/api/v1/attachment`) || PathPrefix(`/api/v1/upload`)"
      middlewares:
        - auth
      service: upload
      tls:
        certResolver: certificates
    lumen:
      rule: "Host(`abc`) && PathPrefix(`/api/v1`)"
      middlewares:
        - auth
      service: lumen
      tls:
        certResolver: certificates
  services:
    auth:
      loadBalancer:
        servers:
          - url: http://proxy:5000
    proxy:
      loadBalancer:
        servers:
          - url: http://proxy:5000
    upload:
      loadBalancer:
        servers:
          - url: http://upload:5005
    lumen:
      loadBalancer:
        servers:
          - url: http://192.168.108.108:9000
  middlewares:
    auth:
      forwardAuth:
        address: "http://proxy:5000/api/v1/auth/verify"
        authResponseHeaders:
          - "Grpc-Metadata-X-Auth-User"
          - "Grpc-Metadata-X-Auth-Keystore"
          - "Grpc-Metadata-X-Auth-Keystore-Used"
        trustForwardHeader: true
    auth1:
      forwardAuth:
        address: "http://proxy:5000/api/v1/auth/verify"
        authResponseHeaders:
          - "Grpc-Metadata-X-Auth-User"
          - "Grpc-Metadata-X-Auth-Keystore"
          - "Grpc-Metadata-X-Auth-Keystore-Used"
        trustForwardHeader: true
    auth2:
      forwardAuth:
        address: "http://proxy:5000/api/v1/auth/verify"
        authResponseHeaders:
          - "Grpc-Metadata-X-Auth-User"
          - "Grpc-Metadata-X-Auth-Keystore"
          - "Grpc-Metadata-X-Auth-Keystore-Used"
        trustForwardHeader: true
    auth3:
      forwardAuth:
        address: "http://proxy:5000/api/v1/auth/verify"
        authResponseHeaders:
          - "Grpc-Metadata-X-Auth-User"
          - "Grpc-Metadata-X-Auth-Keystore"
          - "Grpc-Metadata-X-Auth-Keystore-Used"
        trustForwardHeader: true
    auth4:
      forwardAuth:
        address: "http://proxy:5000/api/v1/auth/verify"
        authResponseHeaders:
          - "Grpc-Metadata-X-Auth-User"
          - "Grpc-Metadata-X-Auth-Keystore"
          - "Grpc-Metadata-X-Auth-Keystore-Used"
        trustForwardHeader: true
    auth5:
      forwardAuth:
        address: "http://proxy:5000/api/v1/auth/verify"
        authResponseHeaders:
          - "Grpc-Metadata-X-Auth-User"
          - "Grpc-Metadata-X-Auth-Keystore"
          - "Grpc-Metadata-X-Auth-Keystore-Used"
        trustForwardHeader: true
tls:
  certificates:
    - certFile: /path/to/public.cert
      keyFile: /path/to/private.key